# language: java

# #dist: trusty
# sudo: false

# script: 
# - ./mvnw -B -U -fae -e -Pserver-distro clean verify

# jdk:
# - oraclejdk8

# addons:
#   apt:
#     packages:
#       - oracle-java8-installer

# cache:
#   directories:
#   - $HOME/.m2
#   - $HOME/.sonar/cache
#   - $HOME/.gradle/

language: java

os:
- osx

script: 
- ./mvnw -B -U -fae -e -Pserver-distro clean verify

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  - $HOME/.gradle/
  